public/heading/nsew.html
Based on [this](https://es.m.wikipedia.org/wiki/Archivo:Rosa_de_los_vientos.svg)
=> add compass rose spanish translations

public/leaflet.html
Hi,
The panTo function is now properly invoked. 
[Some footage available here](https://www.twitch.tv/videos/1033781360)
=> Fix leaflet overlay

public/altitude/feet.html, public/altitude/meters.html, public/distance/distance.js, public/generic.html, public/gta.html, public/heading/deg.html, public/heading/nsew.html, public/mapbox.html, public/neighborhood.html, public/speed/kph.html, public/speed/mph.html
Hi,
Updated the listeners except the one using google.
I did some [testing](https://www.twitch.tv/videos/1035453925)
And the base url if you want to check them out: `https://juaoose.github.io/rtirl-obs/public`
=> Update most event listeners to new api spec

public/index.html
I added a simple section explaining how to embed in SE overlays.
I'm not sure on what the best section might be, please let me know. (Or if I should add a note in the initial sections like the Prims Live one)
=> add streamelements instructions

public/speed/kph.html, public/speed/mph.html
This sets the speed to 0 instead of a negative value.
=> fix: use zero for speed when -1 is the current value

public/index.html, public/neighborhood.html
This is an example where the overlay editor is a lot more helpful than telling people to write URL parameters :)
=> feat: add ability to configure formatting of neighborhood string

web-editor/public/google_preview.html, web-editor/src/component/ConsolePanel.jsx, web-editor/src/component/GoogleMapContainer.jsx, web-editor/src/component/MapboxMapContainer.jsx, web-editor/src/component/RightPanel.jsx, web-editor/src/component/Settings.jsx, web-editor/src/screen/EditorScreen.jsx
Makes the map editor *usable* on mobile, also, got rid of the `Lat, Long, Zoom` string as the only valuable part is the zoom, which is now in the settings panel.
=> chore: improve map layout

web-editor/src/App.js, web-editor/src/screen/TemperatureEditor.jsx
=> feat: add temperature editor

web-editor/src/component/CountryPicker.tsx, web-editor/src/screen/ClockEditor.jsx
Update format capitalization and select max height.
=> chore: update clock styles and capitalization

web-editor/public/google_preview.html, web-editor/src/component/ConsolePanel.jsx, web-editor/src/component/GoogleMapContainer.jsx, web-editor/src/component/RightPanel.jsx, web-editor/src/component/Settings.jsx
Adds zoom control for the google maps editor.
Also disables zooming on the iframe.
=> feat: add zoom to googlemaps editor

web-editor/src/App.js, web-editor/src/index.js
Load pull key from query params `?pullKey=something` so that we can make the process faster when redirected from rtirl.com
Closes #64
=> feat: load pull key from query params

README.md
=> docs: migrate overlays.rtirl.com to README

web-editor/src/App.js, web-editor/src/component/PullKeyInput.jsx, web-editor/src/hooks/usePullKey.js
This also makes sure the pull key is validated when we initially set it
from the query parameters.
=> refactor: extract pull key status and add validation

public/404.html
404, Not Found? What could be better?
=> chore: update 404 page

web-editor/src/component/TextOverlayPreview.jsx, web-editor/src/component/TextSettings.jsx, web-editor/src/hooks/useStyle.js
According to react it could lead to bugs
=> fix: replace order with individual properties

web-editor/src/component/CopyIconTextField.jsx
=> fix: remove URL

web-editor/src/screen/Home.jsx
=> fix: top-padding for title in home page

api/package.json
Closes #122 
I believe this would classify for a major version change right? Since it should break old imports
=> fix(api): update export so that importing the api is more natural

public/leaflet.html
- Fix fullscreen parameter.
- Add `attribution` query parameter to disable attributions.
- Update leaflet version.
=> feat: upgrade leaflet overlay

web-editor/src/screen/NeighborhoodEditor.jsx
=> fix: comma instead of space in encoding url

public/inclination/inclination.js, public/inclination/slope.html
Initial version, needs testing! Works best with 10/100 meter updates.
=> Slope Percentage Overlay v1

web-editor/src/component/OverlayExportPanel.jsx
There probably is a better solution but sending this as its breaking map editors.
=> fix: check that css state is passed

web-editor/src/component/BorderRadiusPicker.jsx, web-editor/src/component/TextSettings.jsx, web-editor/src/utility.js
=> fix: clamp values in text-edits

web-editor/src/App.js, web-editor/src/component/Appbar.jsx, web-editor/src/component/CopyIconTextField.jsx, web-editor/src/component/CountryPicker.tsx, web-editor/src/component/FontPicker.jsx, web-editor/src/component/OverlayExportPanel.jsx, web-editor/src/component/PullKeyInput.jsx, web-editor/src/component/TextSettings.jsx, web-editor/src/screen/ClockEditor.jsx
Sorry if this pull request seems large. Was trying to minimize changes i needed to make and spread it out to upcoming pull requests.
=> style: update sidebar for clock overlay

web-editor/src/screen/InclinationEditor.jsx
=> style: update sidebar for inclination overlay

web-editor/src/screen/AltitudeEditor.jsx
=> style: update sidebar for altitude overlay

web-editor/src/screen/DistanceEditor.jsx
=> style: update sidebar for distance overlay

web-editor/src/screen/HeadingEditor.jsx
=> style: update sidebar for heading overlay

README.md, public/distance/km.html, public/distance/miles.html
Separated links for Beta features to be same as other links, also fixed typo in "Initializing"
=> Formatting and typo fix

firebase.json
=> Revert "fix: change http header for google street view overlay"

firebase.json
=> Revert "fix: change link for http header"

web-editor/src/component/PullKeyInput.jsx, web-editor/src/component/ZoomSlider.jsx, web-editor/src/component/google-maps/GoogleMapsSettings.jsx, web-editor/src/screen/GoogleMapsEditor.jsx
I didn't fully test this change since i don't have a google maps API key with proper permissions but it should work.
closes #210
=> style: update sidebar for google maps overlay 

web-editor/src/App.js
=> fix: add default pull key

public/datetime/luxon.html
http://github.com/kevmo314/browser-geo-tz if you're curious
=> feat: resolve timezone locally

web-editor/src/screen/NeighborhoodEditor.jsx
Fixes https://discord.com/channels/823598483255722056/823598483692453938/1231925665964625960
=> fix: add language to neighborhood overlay url

web-editor/src/App.js, web-editor/src/component/OverlayPreview.jsx, web-editor/src/screen/HeartRateEditor.jsx, web-editor/src/screen/Home.jsx
Add a new editor for `heart_rate/bpm.html` in the web editor.
* **HeartRateEditor Component**:
- Create a new file `HeartRateEditor.jsx` in `web-editor/src/screen/`.
- Import necessary dependencies from `@mui/material`, `react`, and other components.
- Define the `HeartRateEditor` function component.
- Implement the component to include `PullKeyInput`, `OverlayExportPanel`, `TextSettings`, and `TextOverlayPreview`.
- Export the `HeartRateEditor` component as the default export.
* **App.js**:
- Import the `HeartRateEditor` component from `./screen/HeartRateEditor`.
- Add a new route for the heart rate editor in the `Routes` component.
- Ensure the new route uses the `HeartRateEditor` component and passes necessary props.
* **Home.jsx**:
- Import the heart rate image for the overlay …
=> feat: create an editor for heart_rate/bpm.html

web-editor/src/theme/editorTheme.jsx
Last time I opened the editor i thought it was something else but not a scroll bar...
=> chore: update scrollbar

public/inclination/inclination.js
There probably is a better solution, I just wanted to get a fix from seeing it on Terry's stream today.
=> fix(inclination): prevent some NaN scenarios
